device: 0

data:
  image_size: [228, 304]
  lidar_size: 70

model:
  backbone: "efficientnetb0"
  bin_size: 128
  decoder_type: 0 # 0-Trans Conv / 1-Interpolate
  decoder_dim: 16
  num_head: 8
  emb_dim: 128

train: # Adam Optimizer
  tag: "Ref_train_param"
  batch_size: 40
  epochs: 20
  lr: 0.0002
  lr_decay: 0.2
  decay_epoch: [10]
  weight_decay: 0.0005
  alpha: 10.0 # SILog Loss Weight
  beta: 0.1 # Chamfer Loss Weight
  gamma: 0.1 # MinMax Loss Weight